name: CI
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: { node-version: '14' }
    - run: npm install
    - run: npm test
    - name: Build & Push Docker
      run: |
        echo ${{ secrets.DOCKER_PAT }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t ${{ secrets.DOCKER_USERNAME }}/graphql-k8s-demo:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/graphql-k8s-demo:latest
    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl rollout restart deployment/graphql-api