name: Keep-Alive Ping

on:
  schedule:
    # Runs every day at 07:00 UTC; adjust minute/hour as needed
    - cron: '0 7,19 * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping homepage
        run: |
          curl -fsS https://studio.apollographql.com/sandbox/explorer || echo "Ping failed"
